//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJSW_WebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hydlstation> hydlstation { get; set; }
        public virtual DbSet<rain> rain { get; set; }
        public virtual DbSet<SerialPort> SerialPort { get; set; }
        public virtual DbSet<soildata> soildata { get; set; }
        public virtual DbSet<soilstation> soilstation { get; set; }
        public virtual DbSet<ST_ZQ_B> ST_ZQ_B { get; set; }
        public virtual DbSet<SubCenter> SubCenter { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<voltage> voltage { get; set; }
        public virtual DbSet<WarningInfo> WarningInfo { get; set; }
        public virtual DbSet<water> water { get; set; }
    }
}
