//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJSW_WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hydlstation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hydlstation()
        {
            this.rain = new HashSet<rain>();
            this.voltage = new HashSet<voltage>();
            this.water = new HashSet<water>();
        }
    
        public string StationID { get; set; }
        public int SubCenterID { get; set; }
        public string CName { get; set; }
        public string CType { get; set; }
        public Nullable<decimal> WBase { get; set; }
        public Nullable<decimal> WMax { get; set; }
        public Nullable<decimal> WMin { get; set; }
        public Nullable<decimal> WChange { get; set; }
        public Nullable<decimal> RAccuracy { get; set; }
        public Nullable<decimal> RChange { get; set; }
        public string Gsm { get; set; }
        public string Gprs { get; set; }
        public string BDSatellite { get; set; }
        public string BDmember { get; set; }
        public Nullable<decimal> VoltageMin { get; set; }
        public string maintran { get; set; }
        public string subtran { get; set; }
        public string dataprotocol { get; set; }
        public string watersensor { get; set; }
        public string rainsensor { get; set; }
        public string reportinterval { get; set; }
    
        public virtual hydlstation hydlstation1 { get; set; }
        public virtual hydlstation hydlstation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rain> rain { get; set; }
        public virtual SubCenter SubCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voltage> voltage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<water> water { get; set; }
    }
}
