//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJSW_WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_ZQ_B
    {
        public string stationid { get; set; }
        public System.DateTime BGTM { get; set; }
        public int PTNO { get; set; }
        public Nullable<decimal> ZR { get; set; }
        public Nullable<decimal> Q1 { get; set; }
        public Nullable<decimal> Q2 { get; set; }
        public Nullable<decimal> Q3 { get; set; }
        public Nullable<decimal> Q4 { get; set; }
        public Nullable<decimal> Q5 { get; set; }
        public Nullable<decimal> Q6 { get; set; }
        public int currQ { get; set; }
    }
}
