//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJSW_WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningInfo
    {
        public long InfoID { get; set; }
        public string StationID { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public string InfoDetail { get; set; }
        public string ErroCode { get; set; }
    }
}
